In [1]:
import pandas as pd #data processing, CSV file I/O (e.g. pd.read_csv) 
import numpy as np #linear algebra 
from sklearn.multiclass import OneVsRestClassifier
#import accurecy_library for scoring attributes

from sklearn.metrics import accuracy_score

#importing the dataset
df = pd.read_csv('C:\\Users\\Ariful\\Desktop\\final data\\thesisfinaldata1.csv')
#df = pd.read_csv('C:\\Users\\Ariful\\Desktop\\final data\\testsample6.csv')


#filling null value as 0
df=df.fillna('0')

#Dropping Age column
df = df.drop(['Age'], axis= 1)
df = df.drop(['Age2'], axis= 1)
#Dropping Perm_Address column
df = df.drop(['Perm_Address'], axis= 1)

#taking independent variable
X = df.iloc[:,1:22].values
#taking dependent variable
y = df.iloc[:,-1].values

#print("\nX before making numerical: \n",X)
#print("\ny before making numerical: \n",y)

#taking careof categorical data
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
for i in range(0,21):
    X[:,i]= labelencoder_X.fit_transform(X[:,i])

labelencoder_y = LabelEncoder()
y= labelencoder_y.fit_transform(y)

#print("\nX after making numerical: \n",X)
#print("\ny after making numerical: \n",y)

for i in range(1,30):
    # split data train 90 % and test 10 %
    from sklearn.cross_validation import train_test_split
    #X_train=X,y_train=y
    X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.1, random_state = i)
    
    #import random forest classifier 
    from sklearn.ensemble import RandomForestClassifier

    #taking different peremater for random forest classifier
    clf = RandomForestClassifier(n_estimators=80, max_depth=20,criterion='gini',max_features='auto',bootstrap='True',  random_state=42,min_samples_leaf= 2)
    #fitting is equal to training. Then, after it is trained, the model can be used to make predictions, usually with a .predict() method call.
    y_score=clf.fit(X_train, y_train)

    #find out the predicted value
    predicted = clf.predict(X_test)

    #print("Prediction Result: ",predicted)

    #finding actual prediction compared with test size
    print("Accuracy: ",accuracy_score(y_test, predicted, normalize = True)) #accuracy_score(train output, predict output)

C:\Users\Ariful\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


Accuracy:  0.5957446808510638
Accuracy:  0.574468085106383
Accuracy:  0.6808510638297872
Accuracy:  0.5531914893617021
Accuracy:  0.5957446808510638
Accuracy:  0.6170212765957447
Accuracy:  0.6595744680851063
Accuracy:  0.6808510638297872
Accuracy:  0.5106382978723404
Accuracy:  0.6170212765957447
Accuracy:  0.6808510638297872
Accuracy:  0.5319148936170213
Accuracy:  0.6382978723404256
Accuracy:  0.723404255319149
Accuracy:  0.6595744680851063
Accuracy:  0.48936170212765956
Accuracy:  0.5957446808510638
Accuracy:  0.8085106382978723
Accuracy:  0.6382978723404256
Accuracy:  0.46808510638297873
Accuracy:  0.5106382978723404
Accuracy:  0.5319148936170213
Accuracy:  0.6382978723404256
Accuracy:  0.48936170212765956
Accuracy:  0.6595744680851063
Accuracy:  0.723404255319149
Accuracy:  0.6170212765957447
Accuracy:  0.6595744680851063
Accuracy:  0.6382978723404256


In [2]:
#import library for classification report, confusion matrix
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test,predicted))  
print(classification_report(y_test,predicted))

[[ 0  0  0  0  0  0  0  0  1  0]
 [ 0  8  0  0  0  0  0  0  3  0]
 [ 0  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  1  0]
 [ 0  1  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  2  0]
 [ 0  0  0  0  0  0  0  0  3  0]
 [ 0  3  0  0  0  0  0  0 22  0]
 [ 0  0  0  0  0  0  0  0  1  0]]
             precision    recall  f1-score   support

          1       0.00      0.00      0.00         1
          2       0.67      0.73      0.70        11
          7       0.00      0.00      0.00         1
         12       0.00      0.00      0.00         1
         21       0.00      0.00      0.00         1
         22       0.00      0.00      0.00         1
         24       0.00      0.00      0.00         2
         26       0.00      0.00      0.00         3
         27       0.63      0.88      0.73        25
         28       0.00      0.00      0.00         1

avg / total       0.49      0.64      0.55        47



C:\Users\Ariful\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [3]:
# Applying k-Fold Cross Validation
from sklearn.model_selection import cross_val_score
#estimator = object, step = int or float, optional(default = 1), cv = int, cross-validation or an iterable optional
#scoring = string, callable or none, optional, default = none 
accuracies = cross_val_score(estimator = clf, X = X_train, y = y_train, cv = 10)
#taking 10 cv result and find mean value
a=accuracies.mean()
print(a)
print(accuracies)



C:\Users\Ariful\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


0.6042712806565791
[0.40322581 0.53061224 0.64285714 0.68292683 0.51282051 0.62162162
 0.62162162 0.59459459 0.7027027  0.72972973]


In [4]:
# Applying Grid Search to find the best model and the best parameters
from sklearn.model_selection import GridSearchCV
#creat variable param_grid where different perameters are taken
param_grid = { 
          "n_estimators" : [ 30,50,80,100],
           "max_depth" : [ 15, 20,25],
           "min_samples_leaf" : [2,3,4,5]}

#estimator = object, step = int or float, optional(default = 1), cv = int, cross-validation or an iterable optional
#scoring = string, callable or none, optional, default = none
CV_rfc = GridSearchCV(estimator=clf, param_grid=param_grid, cv= 10)
#fitting is equal to training. Then, after it is trained, the model can be used to make predictions, usually with a .predict() method call.
CV_rfc.fit(X_train, y_train)
#taking best score
best_accuracy = CV_rfc.best_score_
print (best_accuracy)
#storing CV_rfc.best_params_ in variable a
a=CV_rfc.best_params_
print (a)

C:\Users\Ariful\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


0.6124401913875598
{'max_depth': 15, 'min_samples_leaf': 4, 'n_estimators': 100}


In [5]:
#printing predicted and actual predicted
print (predicted)
print (y_test)


[27 27 27 27  2  2 27  2 27 27 27 27 27 27 27 27  2  2 27 27 27 27  2 27
 27 27 27 27 27 27 27 27 27  2 27 27 27  2  2 27  2 27 27 27  2  2 27]
[ 1 26  2 27 27  2 27  2 22 24 27 26 27 28 27 27  2  2 27 27 27 26  2 27
 12 27 27 24 27 27  2 27 27 27 27 27 27  2 27 27  2 27  2 27 21  2  7]


In [6]:
df.head(5)

Name Age1 Gender Marital_status Department_Unit  \
0  Anuradha Mistry    2      0              3               4   
1           Sahana    3      0              1               1   
2            Beuty    4      0              1               3   
3    Bristi Akhter    2      0              3               0   
4           Samima    4      0              1               0   

  C1-self laughing C2-self crying C3-Self talking C4-Talkactiveness C5-Food  \
0                1              0               1                 1       1   
1                0              0               0                 0       1   
2                0              1               1                 1       0   
3                0              0               0                 1       1   
4                0              0               0                 1       0   

       ...       C9-outgoing tendency C10-aggressive behaviour  \
0      ...                          0                        0   
1      ...                          0                        0   
2      ...                          1                        0   
3      ...                          1                        0   
4      ...                          0                        1   

  C11-odd behaviour C12-hearing voice C13-speech C14-low mood C15-suicide  \
0                 0                 0          0            0           0   
1                 0                 0          0            0           0   
2                 0                 0          0            0           0   
3                 0                 0          1            0           0   
4                 0                 0          0            0           0   

  C16-lack of self care C17-abuse      Diagnosis  
0                     1         0  Schizophrenia  
1                     0         0            BMD  
2                     0         0  Schizophrenia  
3                     0         0            BMD  
4                     0         0            BMD  

[5 rows x 23 columns]

In [7]:
df["Diagnosis"].groupby(df["Diagnosis"],axis=0).count()


Diagnosis
0                                   2
Acute Psychotic Disorder            6
BMD                               144
BMT                                 1
BPD                                 1
Behavioural disorder                1
Conduct disorder                    2
Conversation disorder              11
DM                                  1
Delusional                          5
Dementia                            2
Depression                          4
EPS                                 1
F.K                                 2
Headache                            1
Internel addictiom                  1
MDD                                 4
N.O.S                               2
NDD                                 1
PTSD                                1
Panaroid sehesophre                 2
Post Partum Psychosis               2
Post Partum Psychotic disorder      1
Psychotic                           1
Psychotic disorder                 23
RBD (CP)                            1
SR